export const adminActionDefinitions = [
    {
        id: 'sync-market',
        title: '刷新行情数据',
        description: '触发 `/api/v1/admin/sync-market`，重建行情聚合条形数据。',
        path: '/admin/sync-market',
        defaults: {},
        fields: [],
        buildParams: () => ({}),
    },
    {
        id: 'sync-factors',
        title: '刷新因子数据',
        description: '触发 `/api/v1/admin/sync-factors`，同步最新因子快照。',
        path: '/admin/sync-factors',
        defaults: {},
        fields: [],
        buildParams: () => ({}),
    },
    {
        id: 'run-model',
        title: '执行模型推演',
        description: '触发 `/api/v1/admin/run-model`，按后端当前实现执行完整模型管线。',
        path: '/admin/run-model',
        defaults: {},
        fields: [],
        buildParams: () => ({}),
    },
    {
        id: 'run-ai-analysis',
        title: '执行 AI 分析',
        description: '触发 `/api/v1/admin/prediction/ai-analysis/regenerate`，基于当前模型结果重生成企业侧与银行侧分析。',
        path: '/admin/prediction/ai-analysis/regenerate',
        defaults: {},
        fields: [],
        buildParams: () => ({}),
    },
    {
        id: 'sync-news',
        title: '同步新闻',
        description: '支持常规同步与从数据库末尾日期向当前时间的增量补抓。',
        path: '/admin/sync-news',
        defaults: {
            catch_up: true,
            page_limit: '200',
            article_limit: '',
            stale_page_limit: '1',
            workers: '4',
        },
        fields: [
            { name: 'catch_up', label: '启用补抓模式', type: 'checkbox', help: '开启后只抓数据库末尾日期之后的新文章。' },
            { name: 'page_limit', label: '列表页上限', type: 'number', min: 1, placeholder: '留空走后端默认值' },
            { name: 'article_limit', label: '文章上限', type: 'number', min: 1, placeholder: '常规同步时常用' },
            { name: 'stale_page_limit', label: '连续陈旧页阈值', type: 'number', min: 1 },
            { name: 'workers', label: '线程数', type: 'number', min: 1 },
        ],
        buildParams: (form) => ({
            catch_up: form.catch_up ? '1' : '0',
            page_limit: form.page_limit,
            article_limit: form.article_limit,
            stale_page_limit: form.stale_page_limit,
            workers: form.workers,
        }),
    },
    {
        id: 'import-news-history',
        title: '导入历史新闻',
        description: '把本地历史新闻全文导入数据库，并补跑分析。',
        path: '/admin/import-news-history',
        defaults: {
            batch_size: '200',
            limit: '',
            resume: true,
            workers: '4',
            executor: 'auto',
        },
        fields: [
            { name: 'batch_size', label: '批大小', type: 'number', min: 1 },
            { name: 'limit', label: '导入数量上限', type: 'number', min: 1, placeholder: '留空表示不限制' },
            { name: 'resume', label: '启用断点续传', type: 'checkbox', help: '从上次最后文件继续，避免重复导入。' },
            { name: 'workers', label: '并行 worker 数', type: 'number', min: 1 },
            {
                name: 'executor',
                label: '执行器',
                type: 'select',
                options: [
                    { value: 'auto', label: 'auto' },
                    { value: 'process', label: 'process' },
                    { value: 'thread', label: 'thread' },
                ],
            },
        ],
        buildParams: (form) => ({
            batch_size: form.batch_size,
            limit: form.limit,
            resume: form.resume ? '1' : '0',
            workers: form.workers,
            executor: form.executor,
        }),
    },
    {
        id: 'reanalyze-news',
        title: '重跑新闻分析',
        description: '对已入库新闻重新执行 NLP 分析，保留原始文章数据。',
        path: '/admin/reanalyze-news',
        defaults: {
            batch_size: '200',
            limit: '',
        },
        fields: [
            { name: 'batch_size', label: '批大小', type: 'number', min: 1 },
            { name: 'limit', label: '重分析数量上限', type: 'number', min: 1, placeholder: '留空表示全部' },
        ],
        buildParams: (form) => ({
            batch_size: form.batch_size,
            limit: form.limit,
        }),
    },
];
